# Optional Exercise:

# Suppose that you’d like to implement a CS50 “shirtificate,” a PDF with an image of an I took CS50 t-shirt,
# shirtificate.png, customized with a user’s own name.

# In a file called shirtificate.py, implement a program that prompts the user for their name and outputs,
# using fpdf2, a CS50 shirtificate in a file called shirtificate.pdf similar to this one for John Harvard,
# with these specifications:

#    The orientation of the PDF should be Portrait.
#    The format of the PDF should be A4, which is 210mm wide by 297mm tall.
#    The top of the PDF should say “CS50 Shirtificate” as text, centered horizontally.
#    The shirt’s image should be centered horizontally.
#    The user’s name should be on top of the shirt, in white text.
#    All other details we leave to you. You’re even welcome to add borders, colors, and lines.
#    Your shirtificate needn’t match John Harvard’s precisely. And no need to wrap long names across multiple lines.

# Before writing any code, do read through fpdf2’s tutorial to learn how to use it. Then skim fpdf2’s API
# (application programming interface) to see all of its functions and parameters therefor.

# Import the FPDF package from fpdf
from fpdf import FPDF

# Ask the user for his/her input name
user_input = input("Name: ")

# Step 1: Create a pdf with portrait orientation and A4 sized
pdf = FPDF(orientation = "P", unit = "mm", format = (210, 297))

# Step 2: Add the pdf page (from the documentation steps)
pdf.add_page()

# Step 3.1: Set the font of the centre text (big size)
# Step 3.2: Place the text CS50 Shirtificate and centre-align it
pdf.set_font("helvetica", style = "B", size = 40)
pdf.cell(210, 10, "CS50 Shirtificate", align = "C")

# Step 4: Upload the image shirtificate.png into the pdf file
# NB: The values of x, y and w are autogenerated
pdf.image("shirtificate.png", x = 10, y = 50, w = 190)

# Step 5.1: Set the text color on the shirt to white (rgb values 255 for all)
# Step 5.2: Set the font of the text on the shirt (smaller size)
# Step 5.3: Place the text {user_input} took CS50 and centre-align it
pdf.set_text_color(255, 255, 255)
pdf.set_font("helvetica", style="B", size=24)
pdf.set_y(120)
pdf.cell(210, 10, f"{user_input} took CS50", align="C")

# Step 6: Output the final pdf into the shirtificate folder
pdf.output("shirtificate.pdf")
